version: "3.8"                                        # 도커 컴포즈 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  pharmacy_recommendation_redis:                        # 서비스명
    container_name: pharmacy_recommendation_redis       # 컨테이너 이름
    build:  #도커 파일이 있는 위치
      dockerfile: Dockerfile
      context: /redis
    image: dongankim/pharmacy_recommendation_redis  # 컨테이너 생성할 때, 사용할 도커 이미지 지정
    ports:
      - "6379:6379"
  pharmacy_recommendation_database:
    container_name: pharmacy_recommendation_database
    build:
      dockerfile: Dockerfile
      context: /database
    image: dongankim/pharmacy_recommendation_database
    environment:  #환경 변수
      - MARIADB_DATABASE=pharmacy_recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:  # 호스트 디렉토리: 컨테이너 디렉토리
      - /database/config:/etc/mysql/conf.d
      - /database/init:/docker-entrypoint-initdb.d
    ports:  #접근 포트 설정
      - "3306:3306"      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
  pharmacy_recommendation_app:
    container_name: pharmacy_recommendation_app
    build: .
    depends_on:          # DB, REDIS 컨테이너가 실행된 다음 WEB을 실행시킨다. 특정 컨테이너에 대한 의존관계
      - pharmacy_recommendation_database
      - pharmacy_recommendation_redis
    image: dongankim/pharmacy_recommendation_app
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
    ports:
      - "80:8080"
    restart: always # depends on은 실행 순서만 컨트롤 할뿐,
      # 컨테이너 안의 서비스가 실행가능한 상태인지까지는 확인 하지 않기 때문에
    # DB 또는 Redis가 아직 실행가능한 상태가 아니여서 실패하는 경우 재시작 하도록 설정